// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var _this = this;
    return $('#profile_pic').hover((function() {
      return $('#information').fadeIn(250);
    }), (function() {
      return $('#information').fadeOut(250);
    }));
  });

}).call(this);
