// Generated by CoffeeScript 1.4.0
(function() {
  var checkIfAtBottom, contactFadeDuration, determineProfilePicture, fadeInInformation, fadeOutInformation, isMouseOverContact, isMouseOverContent, scrollOffset, shiftWindow;

  isMouseOverContact = false;

  isMouseOverContent = false;

  scrollOffset = 35;

  contactFadeDuration = 1000;

  $(document).ready(function() {
    $('#profile_pic').on('mouseenter', fadeInInformation);
    $('#contact').on('mouseleave', fadeOutInformation);
    $('#contact').on('mouseleave', function() {
      return isMouseOverContact = false;
    });
    $('#contact').on('mouseenter', function() {
      return isMouseOverContact = true;
    });
    $('#links a').on('click', function(event) {
      shiftWindow($($(this).attr('href')).position().top);
      return event.preventDefault();
    });
    $('#main_container').hover((function() {
      isMouseOverContent = true;
      $(this).addClass('toggleFocus');
      if ($(window).scrollTop() !== $(document).height() - $(window).height()) {
        return $('#profile_pic').addClass('toggleProfilePicFocus');
      }
    }), (function() {
      isMouseOverContent = false;
      $(this).removeClass('toggleFocus');
      return $('#profile_pic').removeClass('toggleProfilePicFocus');
    }));
    $(window).on('scroll', checkIfAtBottom);
    $(window).on('scroll', determineProfilePicture);
    $(window).bind('scrollstart', function() {
      if (!isMouseOverContact) {
        return $('#profile_pic').addClass('toggleProfilePicFocus');
      }
    });
    $(window).bind('scrollstop', function() {
      if (!isMouseOverContent) {
        return $('#profile_pic').removeClass('toggleProfilePicFocus');
      }
    });
    return checkIfAtBottom();
  });

  shiftWindow = function(position) {
    return scrollTo(0, position - scrollOffset);
  };

  fadeInInformation = function() {
    $('#profile_pic').attr('src', 'images/profile.png');
    $('#profile_pic').removeClass('toggleProfilePicFocus');
    $('#information').stop(true, true).fadeIn(contactFadeDuration);
    return isMouseOverContact = true;
  };

  fadeOutInformation = function() {
    $('#information').fadeOut(contactFadeDuration);
    isMouseOverContact = false;
    return determineProfilePicture();
  };

  checkIfAtBottom = function() {
    if ($(window).scrollTop() === $(document).height() - $(window).height()) {
      $('#contact').off('mouseleave', fadeOutInformation);
      return $('#information').stop(true, true).fadeIn(contactFadeDuration);
    } else {
      $('#contact').on('mouseleave', fadeOutInformation);
      if (!isMouseOverContact) {
        return $('#information').fadeOut(contactFadeDuration);
      }
    }
  };

  determineProfilePicture = function() {
    var image, projects, scroll, work;
    projects = $('#projects').position().top - scrollOffset - 5;
    work = $('#work').position().top - scrollOffset - 5;
    scroll = $(window).scrollTop();
    image = $('#profile_pic');
    if (!isMouseOverContact) {
      if (scroll === $(document).height() - $(window).height()) {
        $('#profile_pic').removeClass('toggleProfilePicFocus');
        return image.attr('src', 'images/profile.png');
      } else {
        if (scroll < projects) {
          return image.attr('src', 'images/profile_alt_1.png');
        } else if ((projects <= scroll && scroll < work)) {
          return image.attr('src', 'images/profile_alt_2.png');
        } else if (work <= scroll && scroll !== $(document).height() - $(window).height()) {
          return image.attr('src', 'images/profile_alt_3.png');
        } else {
          $('#profile_pic').removeClass('toggleProfilePicFocus');
          return image.attr('src', 'images/profile.png');
        }
      }
    }
  };

}).call(this);
