// Generated by CoffeeScript 1.4.0
(function() {
  var checkIfAtBottom, determineProfilePicture, fadeInInformation, fadeOutInformation, isMouseOverContact, scrollOffset, shiftWindow;

  isMouseOverContact = false;

  scrollOffset = 50;

  $(document).ready(function() {
    $('#profile_pic').on('mouseenter', fadeInInformation);
    $('#contact').on('mouseleave', fadeOutInformation);
    $('#contact').on('mouseleave', function() {
      return isMouseOverContact = false;
    });
    $('#contact').on('mouseenter', function() {
      return isMouseOverContact = true;
    });
    $('#links a').on('click', function(event) {
      shiftWindow($($(this).attr('href')).position().top);
      return event.preventDefault();
    });
    $(window).on('scroll', checkIfAtBottom);
    $(window).on('scroll', determineProfilePicture);
    return checkIfAtBottom;
  });

  shiftWindow = function(position) {
    return scrollTo(0, position - scrollOffset);
  };

  fadeInInformation = function() {
    $('#information').fadeIn(325);
    return isMouseOverContact = true;
  };

  fadeOutInformation = function() {
    $('#information').fadeOut(325);
    return isMouseOverContact = false;
  };

  checkIfAtBottom = function() {
    if ($(window).scrollTop() === $(document).height() - $(window).height()) {
      $('#contact').off('mouseleave', fadeOutInformation);
      return $('#information').fadeIn(325);
    } else {
      $('#contact').on('mouseleave', fadeOutInformation);
      if (!isMouseOverContact) {
        return $('#information').fadeOut(325);
      }
    }
  };

  determineProfilePicture = function() {
    var image, projects, scroll, work;
    projects = $('#projects').position().top - scrollOffset - 5;
    work = $('#work').position().top - scrollOffset - 5;
    scroll = $(window).scrollTop();
    image = $('#profile_pic');
    if (scroll === $(document).height() - $(window).height()) {
      return image.attr('src', 'images/profile.png');
    } else {
      if (scroll < projects) {
        return image.attr('src', 'images/profile_alt_1.png');
      } else if ((projects <= scroll && scroll < work)) {
        return image.attr('src', 'images/profile_alt_2.png');
      } else if (work <= scroll && scroll !== $(document).height() - $(window).height()) {
        return image.attr('src', 'images/profile_alt_3.png');
      } else {
        return image.attr('src', 'images/profile.png');
      }
    }
  };

}).call(this);
